Creating test database for alias 'default' ('file:memorydb_default?mode=memory&cache=shared')...
Found 45 test(s).
Operations to perform:
  Synchronize unmigrated apps: messages, rest_framework, staticfiles
  Apply all migrations: address, admin, auth, authtoken, contenttypes, courses, sessions, users
Synchronizing apps without migrations:
  Creating tables...
    Running deferred SQL...
Running migrations:
  Applying contenttypes.0001_initial... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0001_initial... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying auth.0007_alter_validators_add_error_messages... OK
  Applying auth.0008_alter_user_username_max_length... OK
  Applying auth.0009_alter_user_last_name_max_length... OK
  Applying auth.0010_alter_group_name_max_length... OK
  Applying auth.0011_update_proxy_permissions... OK
  Applying auth.0012_alter_user_first_name_max_length... OK
  Applying address.0001_initial... OK
  Applying users.0001_initial... OK
  Applying address.0002_initial... OK
  Applying address.0003_remove_address_user... OK
  Applying admin.0001_initial... OK
  Applying admin.0002_logentry_remove_auto_add... OK
  Applying admin.0003_logentry_add_action_flag_choices... OK
  Applying authtoken.0001_initial... OK
  Applying authtoken.0002_auto_20160226_1747... OK
  Applying authtoken.0003_tokenproxy... OK
  Applying courses.0001_initial... OK
  Applying courses.0002_course_instructor_course_students... OK
  Applying courses.0003_alter_course_demo_time... OK
  Applying courses.0004_alter_course_demo_time... OK
  Applying sessions.0001_initial... OK
System check identified no issues (0 silenced).
test_duplicate_email_user_creation_422 (test_api.TestAccountsRoutesWithoutAuthentication) ... ok
test_instructor_user_creation_201 (test_api.TestAccountsRoutesWithoutAuthentication) ... ok
test_list_users_by_instructor_200 (test_api.TestAccountsRoutesWithoutAuthentication) ... ok
test_list_users_by_student_403 (test_api.TestAccountsRoutesWithoutAuthentication) ... ok
test_list_users_with_no_token_401 (test_api.TestAccountsRoutesWithoutAuthentication) ... ok
test_login_success_200 (test_api.TestAccountsRoutesWithoutAuthentication) ... ok
test_login_with_invalid_credentials_401 (test_api.TestAccountsRoutesWithoutAuthentication) ... ok
test_login_with_wrong_fields_400 (test_api.TestAccountsRoutesWithoutAuthentication) ... ok
test_student_user_creation_201 (test_api.TestAccountsRoutesWithoutAuthentication) ... ok
test_wrong_data_user_creation_400 (test_api.TestAccountsRoutesWithoutAuthentication) ... ok
test_address_creation_200 (test_api.TestAddress) ... ok
test_address_creation_already_exists_200 (test_api.TestAddress) ... ok
test_address_creation_wrong_data_400 (test_api.TestAddress) ... ok
test_delete_course_by_instructor_204 (test_api.TestCourseDelete) ... /home/keila/q4/entregas/parte2-django/e10-kanvas/venv/lib/python3.9/site-packages/django/db/models/fields/__init__.py:1534: RuntimeWarning: DateTimeField Course.created_at received a naive datetime (2022-03-21 11:14:12.209916) while time zone support is active.
  warnings.warn(
ok
test_delete_course_by_no_user_401 (test_api.TestCourseDelete) ... /home/keila/q4/entregas/parte2-django/e10-kanvas/venv/lib/python3.9/site-packages/django/db/models/fields/__init__.py:1534: RuntimeWarning: DateTimeField Course.created_at received a naive datetime (2022-03-21 11:14:12.977718) while time zone support is active.
  warnings.warn(
ok
test_delete_course_by_student_403 (test_api.TestCourseDelete) ... /home/keila/q4/entregas/parte2-django/e10-kanvas/venv/lib/python3.9/site-packages/django/db/models/fields/__init__.py:1534: RuntimeWarning: DateTimeField Course.created_at received a naive datetime (2022-03-21 11:14:13.569804) while time zone support is active.
  warnings.warn(
ok
test_delete_course_with_invalid_course_id_404 (test_api.TestCourseDelete) ... /home/keila/q4/entregas/parte2-django/e10-kanvas/venv/lib/python3.9/site-packages/django/db/models/fields/__init__.py:1534: RuntimeWarning: DateTimeField Course.created_at received a naive datetime (2022-03-21 11:14:14.341330) while time zone support is active.
  warnings.warn(
ok
test_course_creation_by_instructor_201 (test_api.TestCoursesCreation) ... /home/keila/q4/entregas/parte2-django/e10-kanvas/venv/lib/python3.9/site-packages/django/db/models/fields/__init__.py:1534: RuntimeWarning: DateTimeField Course.created_at received a naive datetime (2022-03-21 11:14:15.110266) while time zone support is active.
  warnings.warn(
ok
test_course_creation_by_no_user_401 (test_api.TestCoursesCreation) ... ok
test_course_creation_by_student_403 (test_api.TestCoursesCreation) ... ok
test_course_creation_duplicate_name_422 (test_api.TestCoursesCreation) ... /home/keila/q4/entregas/parte2-django/e10-kanvas/venv/lib/python3.9/site-packages/django/db/models/fields/__init__.py:1534: RuntimeWarning: DateTimeField Course.created_at received a naive datetime (2022-03-21 11:14:16.660518) while time zone support is active.
  warnings.warn(
ok
test_course_creation_wrong_data_400 (test_api.TestCoursesCreation) ... ok
test_list_courses_200 (test_api.TestCoursesCreation) ... /home/keila/q4/entregas/parte2-django/e10-kanvas/venv/lib/python3.9/site-packages/django/db/models/fields/__init__.py:1534: RuntimeWarning: DateTimeField Course.created_at received a naive datetime (2022-03-21 11:14:17.824099) while time zone support is active.
  warnings.warn(
ok
test_retrieve_invalid_course_404 (test_api.TestCoursesCreation) ... ok
test_retrieve_valid_course_200 (test_api.TestCoursesCreation) ... /home/keila/q4/entregas/parte2-django/e10-kanvas/venv/lib/python3.9/site-packages/django/db/models/fields/__init__.py:1534: RuntimeWarning: DateTimeField Course.created_at received a naive datetime (2022-03-21 11:14:18.799479) while time zone support is active.
  warnings.warn(
ok
test_register_instructor_course_by_instructor_200 (test_api.TestCoursesRegister) ... /home/keila/q4/entregas/parte2-django/e10-kanvas/venv/lib/python3.9/site-packages/django/db/models/fields/__init__.py:1534: RuntimeWarning: DateTimeField Course.created_at received a naive datetime (2022-03-21 11:14:19.562577) while time zone support is active.
  warnings.warn(
ERROR
test_register_instructor_course_by_no_user_401 (test_api.TestCoursesRegister) ... /home/keila/q4/entregas/parte2-django/e10-kanvas/venv/lib/python3.9/site-packages/django/db/models/fields/__init__.py:1534: RuntimeWarning: DateTimeField Course.created_at received a naive datetime (2022-03-21 11:14:20.510807) while time zone support is active.
  warnings.warn(
ERROR
test_register_instructor_course_by_student_403 (test_api.TestCoursesRegister) ... /home/keila/q4/entregas/parte2-django/e10-kanvas/venv/lib/python3.9/site-packages/django/db/models/fields/__init__.py:1534: RuntimeWarning: DateTimeField Course.created_at received a naive datetime (2022-03-21 11:14:21.274210) while time zone support is active.
  warnings.warn(
ERROR
test_register_instructor_course_with_invalid_id_404 (test_api.TestCoursesRegister) ... /home/keila/q4/entregas/parte2-django/e10-kanvas/venv/lib/python3.9/site-packages/django/db/models/fields/__init__.py:1534: RuntimeWarning: DateTimeField Course.created_at received a naive datetime (2022-03-21 11:14:22.221419) while time zone support is active.
  warnings.warn(
ERROR
test_register_instructor_course_with_student_id_422 (test_api.TestCoursesRegister) ... /home/keila/q4/entregas/parte2-django/e10-kanvas/venv/lib/python3.9/site-packages/django/db/models/fields/__init__.py:1534: RuntimeWarning: DateTimeField Course.created_at received a naive datetime (2022-03-21 11:14:23.182192) while time zone support is active.
  warnings.warn(
ERROR
test_register_instructor_course_with_wrong_field_400 (test_api.TestCoursesRegister) ... /home/keila/q4/entregas/parte2-django/e10-kanvas/venv/lib/python3.9/site-packages/django/db/models/fields/__init__.py:1534: RuntimeWarning: DateTimeField Course.created_at received a naive datetime (2022-03-21 11:14:24.175484) while time zone support is active.
  warnings.warn(
ERROR
test_register_instructor_course_wrong_courseId_404 (test_api.TestCoursesRegister) ... /home/keila/q4/entregas/parte2-django/e10-kanvas/venv/lib/python3.9/site-packages/django/db/models/fields/__init__.py:1534: RuntimeWarning: DateTimeField Course.created_at received a naive datetime (2022-03-21 11:14:25.132923) while time zone support is active.
  warnings.warn(
ERROR
test_register_students_course_by_intructor_200 (test_api.TestCoursesRegister) ... /home/keila/q4/entregas/parte2-django/e10-kanvas/venv/lib/python3.9/site-packages/django/db/models/fields/__init__.py:1534: RuntimeWarning: DateTimeField Course.created_at received a naive datetime (2022-03-21 11:14:26.099895) while time zone support is active.
  warnings.warn(
ERROR
test_register_students_course_by_no_user_401 (test_api.TestCoursesRegister) ... /home/keila/q4/entregas/parte2-django/e10-kanvas/venv/lib/python3.9/site-packages/django/db/models/fields/__init__.py:1534: RuntimeWarning: DateTimeField Course.created_at received a naive datetime (2022-03-21 11:14:27.115233) while time zone support is active.
  warnings.warn(
ERROR
test_register_students_course_by_student_403 (test_api.TestCoursesRegister) ... /home/keila/q4/entregas/parte2-django/e10-kanvas/venv/lib/python3.9/site-packages/django/db/models/fields/__init__.py:1534: RuntimeWarning: DateTimeField Course.created_at received a naive datetime (2022-03-21 11:14:27.882879) while time zone support is active.
  warnings.warn(
ERROR
test_register_students_course_invalid_course_id_404 (test_api.TestCoursesRegister) ... /home/keila/q4/entregas/parte2-django/e10-kanvas/venv/lib/python3.9/site-packages/django/db/models/fields/__init__.py:1534: RuntimeWarning: DateTimeField Course.created_at received a naive datetime (2022-03-21 11:14:28.833717) while time zone support is active.
  warnings.warn(
ERROR
test_register_students_course_with_instructor_id_422 (test_api.TestCoursesRegister) ... /home/keila/q4/entregas/parte2-django/e10-kanvas/venv/lib/python3.9/site-packages/django/db/models/fields/__init__.py:1534: RuntimeWarning: DateTimeField Course.created_at received a naive datetime (2022-03-21 11:14:29.782663) while time zone support is active.
  warnings.warn(
ERROR
test_register_students_course_with_invalid_student_id_404 (test_api.TestCoursesRegister) ... /home/keila/q4/entregas/parte2-django/e10-kanvas/venv/lib/python3.9/site-packages/django/db/models/fields/__init__.py:1534: RuntimeWarning: DateTimeField Course.created_at received a naive datetime (2022-03-21 11:14:30.735484) while time zone support is active.
  warnings.warn(
ERROR
test_register_students_course_with_wrong_field_400 (test_api.TestCoursesRegister) ... /home/keila/q4/entregas/parte2-django/e10-kanvas/venv/lib/python3.9/site-packages/django/db/models/fields/__init__.py:1534: RuntimeWarning: DateTimeField Course.created_at received a naive datetime (2022-03-21 11:14:31.691676) while time zone support is active.
  warnings.warn(
ERROR
test_register_students_course_with_wrong_field_type_400 (test_api.TestCoursesRegister) ... /home/keila/q4/entregas/parte2-django/e10-kanvas/venv/lib/python3.9/site-packages/django/db/models/fields/__init__.py:1534: RuntimeWarning: DateTimeField Course.created_at received a naive datetime (2022-03-21 11:14:32.636456) while time zone support is active.
  warnings.warn(
ERROR
test_update_course_by_instructor_200 (test_api.TestCoursesUpdate) ... /home/keila/q4/entregas/parte2-django/e10-kanvas/venv/lib/python3.9/site-packages/django/db/models/fields/__init__.py:1534: RuntimeWarning: DateTimeField Course.created_at received a naive datetime (2022-03-21 11:14:33.223389) while time zone support is active.
  warnings.warn(
ok
test_update_course_by_no_user_401 (test_api.TestCoursesUpdate) ... /home/keila/q4/entregas/parte2-django/e10-kanvas/venv/lib/python3.9/site-packages/django/db/models/fields/__init__.py:1534: RuntimeWarning: DateTimeField Course.created_at received a naive datetime (2022-03-21 11:14:33.993661) while time zone support is active.
  warnings.warn(
ok
test_update_course_by_student_403 (test_api.TestCoursesUpdate) ... /home/keila/q4/entregas/parte2-django/e10-kanvas/venv/lib/python3.9/site-packages/django/db/models/fields/__init__.py:1534: RuntimeWarning: DateTimeField Course.created_at received a naive datetime (2022-03-21 11:14:34.584854) while time zone support is active.
  warnings.warn(
ok
test_update_course_with_conflict_422 (test_api.TestCoursesUpdate) ... /home/keila/q4/entregas/parte2-django/e10-kanvas/venv/lib/python3.9/site-packages/django/db/models/fields/__init__.py:1534: RuntimeWarning: DateTimeField Course.created_at received a naive datetime (2022-03-21 11:14:35.361566) while time zone support is active.
  warnings.warn(
/home/keila/q4/entregas/parte2-django/e10-kanvas/venv/lib/python3.9/site-packages/django/db/models/fields/__init__.py:1534: RuntimeWarning: DateTimeField Course.created_at received a naive datetime (2022-03-21 11:14:35.732619) while time zone support is active.
  warnings.warn(
ok
test_update_invalid_course_404 (test_api.TestCoursesUpdate) ... /home/keila/q4/entregas/parte2-django/e10-kanvas/venv/lib/python3.9/site-packages/django/db/models/fields/__init__.py:1534: RuntimeWarning: DateTimeField Course.created_at received a naive datetime (2022-03-21 11:14:36.166792) while time zone support is active.
  warnings.warn(
ok

======================================================================
ERROR: test_register_instructor_course_by_instructor_200 (test_api.TestCoursesRegister)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/keila/q4/entregas/parte2-django/e10-kanvas/test_api.py", line 630, in test_register_instructor_course_by_instructor_200
    output = response.json()
  File "/home/keila/q4/entregas/parte2-django/e10-kanvas/venv/lib/python3.9/site-packages/django/test/client.py", line 748, in _parse_json
    raise ValueError(
ValueError: Content-Type header is "text/html", not "application/json"

======================================================================
ERROR: test_register_instructor_course_by_no_user_401 (test_api.TestCoursesRegister)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/keila/q4/entregas/parte2-django/e10-kanvas/test_api.py", line 707, in test_register_instructor_course_by_no_user_401
    output = response.json()
  File "/home/keila/q4/entregas/parte2-django/e10-kanvas/venv/lib/python3.9/site-packages/django/test/client.py", line 748, in _parse_json
    raise ValueError(
ValueError: Content-Type header is "text/html", not "application/json"

======================================================================
ERROR: test_register_instructor_course_by_student_403 (test_api.TestCoursesRegister)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/keila/q4/entregas/parte2-django/e10-kanvas/test_api.py", line 687, in test_register_instructor_course_by_student_403
    output = response.json()
  File "/home/keila/q4/entregas/parte2-django/e10-kanvas/venv/lib/python3.9/site-packages/django/test/client.py", line 748, in _parse_json
    raise ValueError(
ValueError: Content-Type header is "text/html", not "application/json"

======================================================================
ERROR: test_register_instructor_course_with_invalid_id_404 (test_api.TestCoursesRegister)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/keila/q4/entregas/parte2-django/e10-kanvas/test_api.py", line 776, in test_register_instructor_course_with_invalid_id_404
    output = response.json()
  File "/home/keila/q4/entregas/parte2-django/e10-kanvas/venv/lib/python3.9/site-packages/django/test/client.py", line 748, in _parse_json
    raise ValueError(
ValueError: Content-Type header is "text/html", not "application/json"

======================================================================
ERROR: test_register_instructor_course_with_student_id_422 (test_api.TestCoursesRegister)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/keila/q4/entregas/parte2-django/e10-kanvas/test_api.py", line 751, in test_register_instructor_course_with_student_id_422
    output = response.json()
  File "/home/keila/q4/entregas/parte2-django/e10-kanvas/venv/lib/python3.9/site-packages/django/test/client.py", line 748, in _parse_json
    raise ValueError(
ValueError: Content-Type header is "text/html", not "application/json"

======================================================================
ERROR: test_register_instructor_course_with_wrong_field_400 (test_api.TestCoursesRegister)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/keila/q4/entregas/parte2-django/e10-kanvas/test_api.py", line 801, in test_register_instructor_course_with_wrong_field_400
    output = response.json()
  File "/home/keila/q4/entregas/parte2-django/e10-kanvas/venv/lib/python3.9/site-packages/django/test/client.py", line 748, in _parse_json
    raise ValueError(
ValueError: Content-Type header is "text/html", not "application/json"

======================================================================
ERROR: test_register_instructor_course_wrong_courseId_404 (test_api.TestCoursesRegister)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/keila/q4/entregas/parte2-django/e10-kanvas/test_api.py", line 731, in test_register_instructor_course_wrong_courseId_404
    output = response.json()
  File "/home/keila/q4/entregas/parte2-django/e10-kanvas/venv/lib/python3.9/site-packages/django/test/client.py", line 748, in _parse_json
    raise ValueError(
ValueError: Content-Type header is "text/html", not "application/json"

======================================================================
ERROR: test_register_students_course_by_intructor_200 (test_api.TestCoursesRegister)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/keila/q4/entregas/parte2-django/e10-kanvas/test_api.py", line 829, in test_register_students_course_by_intructor_200
    output = response.json()
  File "/home/keila/q4/entregas/parte2-django/e10-kanvas/venv/lib/python3.9/site-packages/django/test/client.py", line 748, in _parse_json
    raise ValueError(
ValueError: Content-Type header is "text/html", not "application/json"

======================================================================
ERROR: test_register_students_course_by_no_user_401 (test_api.TestCoursesRegister)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/keila/q4/entregas/parte2-django/e10-kanvas/test_api.py", line 894, in test_register_students_course_by_no_user_401
    output = response.json()
  File "/home/keila/q4/entregas/parte2-django/e10-kanvas/venv/lib/python3.9/site-packages/django/test/client.py", line 748, in _parse_json
    raise ValueError(
ValueError: Content-Type header is "text/html", not "application/json"

======================================================================
ERROR: test_register_students_course_by_student_403 (test_api.TestCoursesRegister)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/keila/q4/entregas/parte2-django/e10-kanvas/test_api.py", line 872, in test_register_students_course_by_student_403
    output = response.json()
  File "/home/keila/q4/entregas/parte2-django/e10-kanvas/venv/lib/python3.9/site-packages/django/test/client.py", line 748, in _parse_json
    raise ValueError(
ValueError: Content-Type header is "text/html", not "application/json"

======================================================================
ERROR: test_register_students_course_invalid_course_id_404 (test_api.TestCoursesRegister)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/keila/q4/entregas/parte2-django/e10-kanvas/test_api.py", line 919, in test_register_students_course_invalid_course_id_404
    output = response.json()
  File "/home/keila/q4/entregas/parte2-django/e10-kanvas/venv/lib/python3.9/site-packages/django/test/client.py", line 748, in _parse_json
    raise ValueError(
ValueError: Content-Type header is "text/html", not "application/json"

======================================================================
ERROR: test_register_students_course_with_instructor_id_422 (test_api.TestCoursesRegister)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/keila/q4/entregas/parte2-django/e10-kanvas/test_api.py", line 969, in test_register_students_course_with_instructor_id_422
    output = response.json()
  File "/home/keila/q4/entregas/parte2-django/e10-kanvas/venv/lib/python3.9/site-packages/django/test/client.py", line 748, in _parse_json
    raise ValueError(
ValueError: Content-Type header is "text/html", not "application/json"

======================================================================
ERROR: test_register_students_course_with_invalid_student_id_404 (test_api.TestCoursesRegister)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/keila/q4/entregas/parte2-django/e10-kanvas/test_api.py", line 944, in test_register_students_course_with_invalid_student_id_404
    output = response.json()
  File "/home/keila/q4/entregas/parte2-django/e10-kanvas/venv/lib/python3.9/site-packages/django/test/client.py", line 748, in _parse_json
    raise ValueError(
ValueError: Content-Type header is "text/html", not "application/json"

======================================================================
ERROR: test_register_students_course_with_wrong_field_400 (test_api.TestCoursesRegister)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/keila/q4/entregas/parte2-django/e10-kanvas/test_api.py", line 994, in test_register_students_course_with_wrong_field_400
    output = response.json()
  File "/home/keila/q4/entregas/parte2-django/e10-kanvas/venv/lib/python3.9/site-packages/django/test/client.py", line 748, in _parse_json
    raise ValueError(
ValueError: Content-Type header is "text/html", not "application/json"

======================================================================
ERROR: test_register_students_course_with_wrong_field_type_400 (test_api.TestCoursesRegister)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/keila/q4/entregas/parte2-django/e10-kanvas/test_api.py", line 1019, in test_register_students_course_with_wrong_field_type_400
    output = response.json()
  File "/home/keila/q4/entregas/parte2-django/e10-kanvas/venv/lib/python3.9/site-packages/django/test/client.py", line 748, in _parse_json
    raise ValueError(
ValueError: Content-Type header is "text/html", not "application/json"

----------------------------------------------------------------------
Ran 45 tests in 32.292s

FAILED (errors=15)
Destroying test database for alias 'default' ('file:memorydb_default?mode=memory&cache=shared')...
